// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocqjnsuenvjvzdrwcgki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jcWpuc3VlbnZqdnpkcndjZ2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5Mjg2NjYsImV4cCI6MjA1NDUwNDY2Nn0.qO3llWNmp-nX8A3bLRzh91zn4xmnpkpkNuExjknlXM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);